[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "glycan-mass-spec-annotator"
version = "2.0.0"
description = "GlycoMind: N-Glycan & O-Glycan Tandem Mass Spectrometry Fragmenter Engine"
readme = "README.md"
authors = [{ name = "Dr. Abu Suraih Sakhri", email = "abusuraih@example.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security/Cryptography",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
glycan-mass-spec-annotator = "glyco_mind.cli:main"

[project.urls]
Homepage = "https://github.com/abusuraihsakhri/glycan-mass-spec-annotator"
Repository = "https://github.com/abusuraihsakhri/glycan-mass-spec-annotator.git"
